[package]
name = "alacritty-emacs"
version = "0.1.0"
edition = "2021"

[lib]
name = "alacritty_emacs"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
alacritty_terminal = "0.25.1"
emacs = "0.19.0"
parking_lot = "0.12"
unicode-width = "0.2"
